INSERT INTO AllItems ( ID,BARCODE, NAME,UNIT,PRICE) VALUES (1, 'ITEM000000', '可口可乐', '瓶', 3.00);
INSERT INTO AllItems ( ID,BARCODE, NAME,UNIT,PRICE) VALUES (2, 'ITEM000001', '雪碧', '瓶', 3.00);
INSERT INTO AllItems ( ID,BARCODE, NAME,UNIT,PRICE) VALUES (3, 'ITEM000002', '苹果', '斤', 5.50);
INSERT INTO AllItems ( ID,BARCODE, NAME,UNIT,PRICE) VALUES (4, 'ITEM000003', '荔枝', '斤', 15.00);
INSERT INTO AllItems ( ID,BARCODE, NAME,UNIT,PRICE) VALUES (5, 'ITEM000004', '电池', '个', 2.00);
INSERT INTO AllItems ( ID,BARCODE, NAME,UNIT,PRICE) VALUES (6, 'ITEM000005', '方便面', '袋', 4.50);

INSERT INTO ForSave (ID, TYPE,BARCODE) VALUES (1, 'BUY_TWO_GET_ONE_FREE', 'ITEM000000');
INSERT INTO ForSave (ID, TYPE,BARCODE) VALUES (2, 'BUY_TWO_GET_ONE_FREE', 'ITEM000001');
INSERT INTO ForSave (ID, TYPE,BARCODE) VALUES (3, 'BUY_TWO_GET_ONE_FREE', 'ITEM000005');

